version: '3.8'

services:
  # Nosso serviço principal da web (A aplicação)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mvc_frankenphp
    ports:
      # A porta da esquerda (Seu PC) aponta para a porta da direita (Dentro do docker virtual)
      - "8000:8000"
    environment:
      - APP_ENV=local
      - DB_HOST=mysql
      - REDIS_HOST=redis
      - MERCURE_PUBLISHER_JWT_KEY=!ChangeThisMercureHubJWTSecretKey!
      - MERCURE_SUBSCRIBER_JWT_KEY=!ChangeThisMercureHubJWTSecretKey!
      - MERCURE_URL=http://localhost:8000/.well-known/mercure
      - MERCURE_PUBLIC_URL=http://localhost:8000/.well-known/mercure
    volumes:
      - .:/app
      - ./Caddyfile:/etc/frankenphp/Caddyfile
    depends_on:
      - redis
      - mysql
    restart: unless-stopped

  # Banco de Dados MySQL
  mysql:
    image: mysql:8
    container_name: mvc_mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-mvc_base}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  # Banco de Dados Redis para Cache e Filas
  redis:
    image: redis:alpine
    container_name: mvc_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  mysql_data:
